baseurl: "/"
title: "The Open Revolution"
languageCode: "en-us"
googleAnalytics: UA-102022428-3
enableRobotsTXT: true

permalinks:
  blog: /:year/:month/:day/:slug/

params:
  twitter: https://twitter.com/@rufuspollock/
  facebook: https://www.facebook.com/RufusPollockOfficial/
  medium: https://medium.com/open-revolution

  UKpaperback: https://www.amazon.co.uk/Open-Revolution-New-rules-world/dp/1983033227
  UKkindle: https://www.amazon.co.uk/Open-Revolution-New-rules-world-ebook/dp/B07DDDFCG6
  USpaperback: https://www.amazon.com/Open-Revolution-New-rules-world/dp/1983033227
  USkindle: https://www.amazon.com/Open-Revolution-New-rules-world-ebook/dp/B07DDDFCG6
  FRpaperback: https://www.amazon.fr/Open-Revolution-New-rules-world/dp/1983033227
  FRkindle: https://www.amazon.fr/Open-Revolution-rules-world-English-ebook/dp/B07DDDFCG6
  rufuspollock:
    path: rufus-pollock.png
    fullname: Rufus Pollock

  okfn:
    fullname: OKFN Blog Post
  
  derfrietag:
    fullname: derFrietag

  elightenmenteco:
    fullname: Enlightenment Economics

  boingboing:
    path: boing-boing.png
    fullname: Boing Boing

  bbc:
    fullname: BBC Click