baseurl: "/"
title: "The Open Revolution"
languageCode: "en-us"
googleAnalytics: ""

permalinks:
  blog: /:year/:month/:day/:slug/

params:
  github: https://github.com/
  twitter: https://twitter.com/@rufuspollock/
  linkedin: https://www.linkedin.com/
  facebook: https://www.facebook.com/rufus.pollock/
